name: Integración con Azure Repos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to Azure Repos
      env:
        AZURE_REPO_URL: https://your-organization.visualstudio.com/YourProject/_git/YourRepo
        AZURE_DEVOPS_TOKEN: ${{secrets.AZURE_DEVOPS_TOKEN}}
      run: |
        git remote add azure-repos $AZURE_REPO_URL
        git config --global user.email "Fernando.Gualo@uclm.es"
        git config --global user.name "FERNANDO GUALO CEJUDO"
        git push azure-repos main
  # git remote add origin https://Gualo@dev.azure.com/Gualo/Test_Git2Repos/_git/Test_Git2Repos
