name: Integración con Azure Repos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push to Azure Repos
      env:
        AZURE_REPO_URL: https://dev.azure.com/Gualo/Test_Git2Repos/_git/Test_Git2Repos
        AZURE_DEVOPS_TOKEN: ${{secrets.AZURE_DEVOPS_TOKEN}}
      run: |
        git config --global user.email "Fernando.Gualo@uclm.es"
        git config --global user.name "Gualo"
        git config --global credential.helper store
        git remote set-url origin https://Gualo:skkbtk4m2atann25wui2rvfp7742p2baavvnnlhk7ct2gdz2wnzq@dev.azure.com/Gualo/Test_Git2Repos/_git/Test_Git2Repos
        git add .
        git push
      #git remote add origin https://Gualo@dev.azure.com/Gualo/Test_Git2Repos/_git/Test_Git2Repos
      #git add .
        
      #git commit -m "Integrando desde Github"
      #git push origin maain
      
      #git config --global user.email "Fernando.Gualo@uclm.es"
      #git config --global user.name "Gualo"
      #git  add origin https://Gualo@dev.azure.com/Gualo/Test_Git2Repos/_git/Test_Git2Repos
      #git remote add azure-repos $AZURE_REPO_URL
      #git config --global user.email "Fernando.Gualo@uclm.es"
      #git config --global user.name "Gualo"
      #git push azure-repos main
        
